### ISSUE TITLE
TypeError: 'module' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by corrado-boscarino** [Data2Semantics/TabLinker#11]
Cannot execute tablinker.py :

corrado@corrado-M4700:~/usr/TabLinker-master/src$ python tablinker.py
INFO:root:Reading configuration file
INFO:root:Found 2 files to convert.
INFO:root:Starting TabLinker for ../input/BRT_1889_02_T1_marked.xls
DEBUG:TabLinker:Initializing Graphs
DEBUG:TabLinker:Adding namespaces to graphs
DEBUG:TabLinker:Adding some schema information (dimension and measure properties) 
Traceback (most recent call last):
  File "tablinker.py", line 661, in <module>
    tLinker = TabLinker(filename, config, logLevel)
  File "tablinker.py", line 64, in **init**
    self.initGraphs()
  File "tablinker.py", line 102, in initGraphs
    self.graph.add((self.namespaces['d2s']['label'], RDF.type, RDF['Property']))
TypeError: 'module' object has no attribute '**getitem**'

**Comment by albertmeronyo** [comment]
Please check that you have the most recent versions of the required libraries:

$ sudo pip install xlrd xlutils rdflib --upgrade

**Comment by corrado-boscarino** [comment]
Thanks,

installing rdflib-3.4.0 fixes the problem (I had 2.4.2)

Corrado.

---

Van: Albert Meroño-Peñuela [notifications@github.com]
Verzonden: woensdag 17 april 2013 15:54
To: Data2Semantics/TabLinker
Cc: Boscarino, C.
Onderwerp: Re: [TabLinker] TypeError: 'module' object has no attribute '**getitem**' (#11)

Please check that you have the most recent versions of the required libraries:

$ sudo pip install xlrd xlutils rdflib --upgrade
