### ISSUE TITLE
running tablinker in cmd from windows fails

### ISSUE THREAD

**Issue by MartineDeVos** [Data2Semantics/TabLinker#7]
INFO:root:Serializing graph to file ../output/input\BRT_1889_02_T1_ma
ERROR:root:Whoops! Something went wrong in serializing to output file
INFO:root:(<type 'exceptions.IOError'>, IOError('File not open for wr
traceback object at 0x00000000031FAD88>)
INFO:root:Done

Probably a path name error (see path of output file)

**Comment by LaurensRietveld** [comment]
Fixed by making creating of basename os independent, and by avoiding rdflib to write the life (buggy). Instead, the turtle is retrieved as string, and written to file by tablinker
